### ISSUE TITLE
Draggable bottom middle grid with a button to play a 2048 game underneath

### ISSUE THREAD

**Issue by LeeWeeder** [LeeWeeder/ljmaq-gsps#2]
### Description
The bottom middle grid of the home screen does not yet have a purpose. Make it draggable and have ~~something~~ a _button to play_ a **2048 GAME** hidden under it that would be visible if the grid is dragged away.

### Specs
1. Any part of the grid could be used to drag the grid.
2. The grid should have a default position (in the bottom middle of the whole container) that when dragged, the grid should follow the pointer or touch but reposition if released.

### TODO

- [x] Brainstorm ideas for what will be hidden underneath.
- [ ] Implement the feature.
- [ ] Program the game.
